export default function Disclaimer() {
  return (
    <div className="bg-tertiary-fixed/35 border-2 border-tertiary-fixed rounded-card p-5 flex items-start gap-4 mb-7">
      <span className="text-2xl flex-shrink-0">⚠️</span>
      <div className="text-[15px] text-on-surface/90 leading-relaxed">
        <p>
          This information is <strong className="text-on-surface">generated by AI</strong> and
          is for general information only — it is{" "}
          <strong className="text-on-surface">NOT medical advice</strong>. Please always
          confirm with your doctor or pharmacist before making any decisions about your
          medicine.
        </p>
        <p className="font-sinhala leading-sinhala mt-2">
          මෙම තොරතුරු <strong className="text-on-surface">AI මගින් සකසන ලද</strong> සාමාන්‍ය
          දැනුමක් පමණි —{" "}
          <strong className="text-on-surface">මෙය වෛද්‍ය උපදෙස් නොවේ</strong>. කරුණාකර ඔබේ
          බෙහෙත් ගැන කිසිම තීරණයක් ගැනීමට පෙර සැමවිටම ඔබේ දොස්තර මහතාගෙන් හෝ ෆාමසියෙන්
          අහන්න.
        </p>
      </div>
    </div>
  );
}
